name: "构建 - Docker Test"

on:
  push:
    branches: [ master, next ]

jobs:
  build:
    strategy:
      matrix:
        platform: [
          "linux/386",
          "linux/amd64",
          "linux/arm/v5",
          "linux/arm/v7",
          "linux/arm/v6",
          "linux/arm64",
          "windows/amd64",
          "darwin/amd64",
          "darwin/arm64"
        ]
    continue-on-error: true        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zhang134/node-oba-fix:dev
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
