name: "Release Binary"

on:
  push:
    tags:
      - 'v*.*.*'  # 仅当推送的标签以 'v' 开头时触发（例如 v1.0.0）

jobs:


  build-update-zip:
    name: "构建 - 增量更新包"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: "安装依赖"
        run: |
          npm i --no-package-lock

      - name: "开始构建"
        run: |
          npm run build

      - name: "打包 update.zip"
        run: |
          zip -r update.zip dist package.json

      - name: "上传文件"
        uses: actions/upload-artifact@v4
        with:
          name: update
          path: |
            dist
            package.json

  upload-to-release:
    name: "打包 - 上传至 Release"
    runs-on: ubuntu-latest
    needs: [build-update-zip]
    steps:
      - name: "下载构建文件"
        uses: actions/download-artifact@v4
  

  
      - name: "重新打包 增量更新包"
        run: |
          cd update
          zip -r ../update.zip *
          cd ..

      - name: "自动生成变更日志"
        run: npx changelogithub-chinese
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}

      - name: "上传至 Release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Node-OBA-Fix-linux-x64.tar.xz.zip
            Node-OBA-Fix-linux-arm64.tar.xz.zip
            Node-OBA-Fix-linux-armv7l.tar.xz.zip            
            Node-OBA-Fix-macos-x64.tar.xz.zip
            Node-OBA-Fix-macos-arm64.tar.xz.zip
            Node-OBA-Fix-windows-x64.tar.gz.zip
            update.zip
