name: "Release Binary"

on:
  push:
    tags:
      - 'v*.*.*'  # 仅当推送的标签以 'v' 开头时触发（例如 v1.0.0）

jobs:


  build-update-zip:
    name: "打包升级压缩包"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm i --no-package-lock
      - run: npm run build

      - name: "打包 update.zip"
        run: |
          zip -r update.zip dist package.json

      - name: "上传文件"
        uses: actions/upload-artifact@v4
        with:
          name: update
          path: |
            dist
            package.json

  upload-to-release:
    name: "上传至Release"
    runs-on: ubuntu-latest
    needs: [build-update-zip]
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4

      - name: "重新打包为ZIP文件"
        run: |
          # Unpack and repack Node-OBA-Fix-linux-x64.tar.xz
          tar -xf Node-OBA-Fix-linux-x64.tar.xz
          cd Node-OBA-Fix-linux-x64
          zip -r ../Node-OBA-Fix-linux-x64.zip *
          cd ..

          # Unpack and repack Node-OBA-Fix-linux-arm64.tar.xz
          tar -xf Node-OBA-Fix-linux-arm64.tar.xz
          cd Node-OBA-Fix-linux-arm64
          zip -r ../Node-OBA-Fix-linux-arm64.zip *
          cd ..

          # Unpack and repack Node-OBA-Fix-macos-x64.tar.xz
          tar -xf Node-OBA-Fix-macos-x64.tar.xz
          cd Node-OBA-Fix-macos-x64
          zip -r ../Node-OBA-Fix-macos-x64.zip *
          cd ..

          # Unpack and repack Node-OBA-Fix-macos-arm64.tar.xz
          tar -xf Node-OBA-Fix-macos-arm64.tar.xz
          cd Node-OBA-Fix-macos-arm64
          zip -r ../Node-OBA-Fix-macos-arm64.zip *
          cd ..

          # Unpack and repack Node-OBA-Fix-windows-x64.tar.gz
          tar -xzf Node-OBA-Fix-windows-x64.tar.gz
          cd Node-OBA-Fix-windows-x64
          zip -r ../Node-OBA-Fix-windows-x64.zip *
          cd ..

          # Unpack and repack Node-OBA-Fix-linux-armv7l.tar.xz
          tar -xf Node-OBA-Fix-linux-armv7l.tar.xz
          cd Node-OBA-Fix-linux-armv7l
          zip -r ../Node-OBA-Fix-linux-armv7l.zip *
          cd ..

          # Repack update folder
          cd update
          zip -r ../update.zip *
          cd ..

      - name: "Upload to Release"
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Node-OBA-Fix-linux-x64.zip
            Node-OBA-Fix-linux-arm64.zip
            Node-OBA-Fix-macos-x64.zip
            Node-OBA-Fix-macos-arm64.zip
            Node-OBA-Fix-windows-x64.zip
            Node-OBA-Fix-linux-armv7l.zip
            update.zip
